version: "3.9"

x-common-env: &common_env
  # Set this VIP/DNS so satellites and clients always hit the active controller
  LINSTOR_CONTROLLERS: "${LINSTOR_CONTROLLERS:-4.0.0.7:3370}"

x-satellite-mounts: &satellite_mounts
  - /etc/linstor:/etc/linstor
  - /var/lib/linstor:/var/lib/linstor
  - /etc/drbd:/etc/drbd
  - /var/lib/drbd:/var/lib/drbd
  - /dev:/dev
  - /sys:/sys
  - /lib/modules:/lib/modules:ro
  - /run/udev:/run/udev:ro

services:
  linstor-controller:
    # Build the controller image straight from source
    build:
      context: https://github.com/mgherghi/linstor-server-full.git#stable
      dockerfile: Dockerfile.controller
    image: linstor-controller:latest
#    image: linstor-controller:latest
    container_name: linstor-controller
    hostname: ${NODE_HOSTNAME:-linstor-controller}
    network_mode: host
    restart: unless-stopped
    environment:
      LINSTOR_ROLE: "both"                 # controller + satellite
      CONTROLLER_BIND_ADDR: "0.0.0.0"
      CONTROLLER_BIND_PORT: "3370"
      LINSTOR_CONTROLLERS: "${LINSTOR_CONTROLLERS:-4.0.0.7:3370}"
    volumes:
      - /etc/linstor:/etc/linstor          # will contain NO [db] in linstor.toml or no file at all
      - /var/lib/linstor:/var/lib/linstor  # H2 lives here by default
      - /etc/drbd:/etc/drbd
      - /var/lib/drbd:/var/lib/drbd
      - /dev:/dev
      - /sys:/sys
      - /lib/modules:/lib/modules:ro
      - /run/udev:/run/udev:ro
      # Provide controller configuration (DB, bind address/port)
      - ./linstor.toml:/etc/linstor/linstor.toml:ro
    healthcheck:
      test: ["CMD-SHELL", "linstor controller list >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 60s

  linstor-satellite:
    # Build the satellite image straight from source
    build:
      context: https://github.com/mgherghi/linstor-server-full.git#stable
      dockerfile: Dockerfile.satellite
    image: linstor-satellite:latest
    container_name: linstor-satellite
    hostname: ${NODE_HOSTNAME:-linstor-satellite}
    network_mode: host
    privileged: true  # simplest path to host DRBD + devices
    restart: unless-stopped
    environment:
      <<: *common_env
    volumes: *satellite_mounts
    # Satellite reads /etc/linstor/satellite.conf (mounted below)
    depends_on:
      linstor-controller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "linstor node list >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 60s
