version: "3.9"

x-common-env: &common_env
  # Set this VIP/DNS so satellites and clients always hit the active controller
  LINSTOR_CONTROLLERS: "${LINSTOR_CONTROLLERS:-linbit-ha.local:3370}"

x-satellite-mounts: &satellite_mounts
  - /etc/linstor:/etc/linstor
  - /var/lib/linstor:/var/lib/linstor
  - /etc/drbd:/etc/drbd
  - /var/lib/drbd:/var/lib/drbd
  - /dev:/dev
  - /sys:/sys
  - /lib/modules:/lib/modules:ro
  - /run/udev:/run/udev:ro

services:
  linstor-controller:
    # Build the controller image straight from source
    build:
      context: https://github.com/LINBIT/linstor-server.git#v1.31.3
      dockerfile: Dockerfile.controller
    image: linstor-controller:src-v1.31.3
    container_name: linstor-controller
    hostname: ${NODE_HOSTNAME:-r730xd-1}
    network_mode: host
    restart: unless-stopped
    environment:
      <<: *common_env
    volumes:
      - /etc/linstor:/etc/linstor
      - /var/lib/linstor:/var/lib/linstor
      # Provide controller configuration (DB, bind address/port)
      - ./linstor.toml:/etc/linstor/linstor.toml:ro
    healthcheck:
      test: ["CMD-SHELL", "linstor controller list >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 60s

  linstor-satellite:
    # Build the satellite image straight from source
    build:
      context: https://github.com/LINBIT/linstor-server.git#v1.31.3
      dockerfile: Dockerfile.satellite
    image: linstor-satellite:src-v1.31.3
    container_name: linstor-satellite
    hostname: ${NODE_HOSTNAME:-r730xd-1}
    network_mode: host
    privileged: true  # simplest path to host DRBD + devices
    restart: unless-stopped
    environment:
      <<: *common_env
    volumes: *satellite_mounts
    # Satellite reads /etc/linstor/satellite.conf (mounted below)
    depends_on:
      linstor-controller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "linstor node list >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 60s

  # Handy toolbox with the LINSTOR CLI & Python API, built from source too
  linstor-client:
    build:
      context: .
      dockerfile: Dockerfile.client-src
    image: linstor-client:src
    container_name: linstor-client
    network_mode: host
    depends_on:
      linstor-controller:
        condition: service_started
    restart: unless-stopped
    environment:
      <<: *common_env
    volumes:
      - /etc/linstor:/etc/linstor
      - /var/lib/linstor:/var/lib/linstor
    command: ["bash", "-lc", "sleep infinity"]
